name: Update Server Status

on:
  schedule:
    - cron: '*/10 * * * *' # Изменено на 10 минут (минимум для стабильности)
  workflow_dispatch:      # Оставляем для ручного запуска
  push:
    branches: [ main ]
    paths-ignore:         # Не запускать экшен, если изменился только этот файл
      - 'server-status.json'

permissions:              # Добавляем права на запись
  contents: write

jobs:
  update-status:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get server status
        run: |
          curl -s "https://api.mcsrvstat.us/2/188.127.241.222:25601" > server-status.json
      
      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add server-status.json
          # Проверка на наличие изменений, чтобы не плодить пустые коммиты
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update server status [skip ci]"
            git push
          fi
